version: '2'
services:
    falconcms-app:
        image: falconcms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://falconcms-postgresql:5432/falconcms
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    falconcms-postgresql:
        extends:
            file: postgresql.yml
            service: falconcms-postgresql
